{% set name = "napari-geojson" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5aac6e57c3a90c195bce0cbccd0c4b487de705de176ad530f0b9d1d37f5b871b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - geojson
    - napari
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_geojson
  commands:
    - pip list
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tdmorello/napari-geojson
  summary: Read and write geojson files in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - goanpeca
    - psobolewskiPhD
    - tdmorello
